name: Telegram Bot Runner

on:
  schedule:
    - cron: "0 */4 * * *" # প্রতি ৪ ঘণ্টা পর পর
  workflow_dispatch: # ম্যানুয়ালি চালানোর অপশন

concurrency:
  group: telegram-bot
  cancel-in-progress: true # আগের রানিং বট বন্ধ করে নতুনটা চালু করবে

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 235
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install pyTelegramBotAPI firebase-admin

      - name: Run Bot Script
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: python bot.py
